# ansible/inventory/hosts.yml
all:
  children:
    docker_containers:
      hosts:
        shellguard-dev:
          ansible_host: shellguard-dev
          ansible_connection: docker
          ansible_user: developer
        shellguard-test:
          ansible_host: shellguard-test
          ansible_connection: docker
          ansible_user: tester
      vars:
        ansible_python_interpreter: /usr/bin/python3

    local:
      hosts:
        localhost:
          ansible_connection: local