# docker/docker-compose.yml
version: '3.8'

services:
  # Development environment with ShellGuard
  dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: shellguard-dev
    volumes:
      - ../:/workspace:rw
      - ~/.ssh:/home/developer/.ssh:ro
      - shellguard-cache:/home/developer/.shellguard
    environment:
      - SHELLGUARD_ENV=development
      - SHELLGUARD_AUTO_BACKUP=true
      - SHELLGUARD_MONITOR=true
    stdin_open: true
    tty: true
    networks:
      - shellguard-net

  # Testing environment
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    container_name: shellguard-test
    volumes:
      - ../:/workspace:ro
      - test-results:/test-results
    environment:
      - SHELLGUARD_ENV=testing
      - SHELLGUARD_AUTO_BACKUP=false
      - SHELLGUARD_STRICT_MODE=true
    networks:
      - shellguard-net
    depends_on:
      - dev

  # Ansible controller
  ansible:
    image: cytopia/ansible:latest
    container_name: shellguard-ansible
    volumes:
      - ../ansible:/ansible:ro
      - test-results:/test-results
      - /var/run/docker.sock:/var/run/docker.sock:ro
    working_dir: /ansible
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      - SHELLGUARD_TEST_MODE=true
    networks:
      - shellguard-net
    depends_on:
      - dev
      - test

volumes:
  shellguard-cache:
  test-results:

networks:
  shellguard-net:
    driver: bridge